---
# tasks file for sonarqube
- name: Set the required sysctl value for Elasticsearch
  ansible.builtin.sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes
- name: create sonqrqube main folder
  file: 
    path: "{{sonarqube_dir}}"
    state: directory
    mode: '0755'
- name: copy docker compose file 
  ansible.builtin.template:
    src: ../templates/sonarqube.yml.j2
    dest: "{{sonarqube_dir}}/sonarqube.yml"
- name: setup sonarqube service
  community.docker.docker_compose_v2:
    project_src: "{{sonarqube_dir}}"
    files:
      - sonarqube.yml
    state: present