---
# tasks file for change-root-password
- name: copy root-password script file for gitlab
  ansible.builtin.template:
    src: ../files/{{ script_file_name }}.j2
    dest: "{{gitlab_dir}}/{{ script_file_name }}"
    mode: '0644'
- name: Copy a file into the container
  community.docker.docker_container_copy_into:
    container: gitlab
    path: "{{ gitlab_dir }}/{{ script_file_name }}"
    container_path: "{{ gitlab_container_path }}/{{ script_file_name }}"
- name: execute script in container
  community.docker.docker_container_exec:
    container: gitlab
    command: /bin/bash -c "gitlab-rails runner {{ gitlab_container_path }}/{{ script_file_name }}"
    chdir: /
- name: remove script from container
  community.docker.docker_container_exec:
    container: gitlab
    command: /bin/bash -c "rm -rf {{ gitlab_container_path }}/{{ script_file_name }}"
    chdir: /
- name: Remove script form gitlab dir
  file:
    path: "{{ gitlab_dir }}/{{ script_file_name }}"
    state: absent