- name: Generate SSH key on master
  become: true 
  hosts: jenkins_server
  prompt_vars:
  vars_prompt:
    - name: jenkins_username
      prompt: "Please enter your jenkins username"
      private: no
    - name: jenkins_password
      prompt: "Please enter your jenkins password"
      private: no
    - name: jenkins_url
      prompt: "Please enter your jenkins controller instance url"
      private: no
  roles:
    - generate-ssh-key