- name: Generate SSH key on master
  become: true 
  hosts: jenkins_server
  roles:
    - generate-ssh-key
- hosts : jenkins_agents
  become: true
  become_user: root
  roles:
    #- prerequisites
    - jenkins_agent_creation
- name: create new node on jenkins master
  become: true 
  hosts: jenkins_server
  roles:
    -  add_jenkins_node