version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://172.18.0.2:80'
    ports:
      - '80:80'
      - '443:443'
      - '2022:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    logging:
      options:
        max-size: 200mb
    #network_mode: host
    networks:
      gitlab_network:
        ipv4_address: 172.18.0.2
networks:
  gitlab_network:
    name: gitlab_network
    driver: bridge
    ipam:
      config:
      -
        subnet: 172.18.0.0/16