- hosts: gitlab-server
  become: true
  vars:
    gitlab_dir: /srv/gitlab/
    gitlab_runner_dir: /srv/gitlab/gitlab-runner/
    config_file: config.toml
  tasks:
  - name: create mount folder for gitlab
    file: 
      path: "{{gitlab_dir}}"
      state: directory
      mode: '0755'
  - name: create mount folder for gitlab-runner
    file: 
      path: "{{gitlab_runner_dir}}/gitlab-runner-config"
      state: directory
      mode: '0755'
  - name: create empty config.toml for gitlab-runner
    copy:
      content: ''
      dest: "{{ gitlab_runner_dir }}/{{ config_file }}"
      mode: '0644'
  - name: copy docker-compose files for gitlab 
    copy:
      src: ./gitlab.yml
      dest: "{{gitlab_dir}}"
      mode: '0644'
  - name: copy root-password-config file for gitlab
    copy:
      src: ./set-root-password.rb
      dest: "{{gitlab_dir}}"
      mode: '0644'
  - name: copy docker-compose files for gitlab-runner
    copy:
      src: ./gitlab-runner.yml
      dest: "{{gitlab_dir}}"
      mode: '0644'
  - name: tear down existing services
    community.docker.docker_compose_v2:
      project_src: "{{gitlab_dir}}"
      files:
        - gitlab.yml
        - gitlab-runner.yml
      state: absent
  - name: Create and start services
    community.docker.docker_compose_v2:
      project_src: /srv/gitlab
      files:
        - gitlab.yml
        - gitlab-runner.yml
      state: present
    register: output
  - name: Debug output
    debug:
      var: output

      