- hosts: gitlab-server
  become: true
  vars:
    gitlab_dir: /srv/gitlab/
    gitlab_container_path : /tmp
    script_file_name : set-root-password.rb
  tasks:
  - name: Copy a file into the container
    community.docker.docker_container_copy_into:
      container: gitlab
      path: "{{ gitlab_dir }}/{{ script_file_name }}"
      container_path: "{{ gitlab_container_path }}/{{ script_file_name }}"
  - name: execute script in container
    community.docker.docker_container_exec:
      container: gitlab
      command: /bin/bash -c "gitlab-rails runner {{ gitlab_container_path }}/{{ script_file_name }}"
      chdir: /
  - name: remove script from container
    community.docker.docker_container_exec:
      container: gitlab
      command: /bin/bash -c "rm -rf {{ gitlab_container_path }}/{{ script_file_name }}"
      chdir: /


#gitlab-rails runner "token = User.find_by_username('root').personal_access_tokens.create(scopes: ['read_user', 'read_repository'], name: 'Automation token', expires_at: 365.days.from_now); token.set_token('token-string-here123'); token.save!"
