- hosts: jenkins_server
  become: true
  vars_prompt:
    - name: jenkins_username
      prompt: "Please enter your jenkins username"
      private: no
    - name: jenkins_password
      prompt: "Please enter your jenkins password"
      private: no
    - name: jenkins_url
      prompt: "Please enter your jenkins controller instance url"
      private: no
  roles :
    - jenkins_plugins_installation