---
# tasks file for generate-ssh-key
- name: create mount folder for jenkins home
  file: 
    path: "{{jenkins_dir}}{{ ssh_key_path }}"
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000
- name: Generate SSH key pair
  ansible.builtin.openssh_keypair:
    path: "{{jenkins_dir}}{{ ssh_key_path }}/{{ssh_key_name}}"
    type: ed25519
    size: 2048
  register: ssh_key
- name: Get the initial admin password for Jenkins
  shell: cat "{{jenkins_dir}}{{ ssh_key_path }}/{{ssh_key_name}}"
  register: private_key
# - name: Display public key
#   ansible.builtin.debug:
#     msg: "{{ private_key.stdout }}"
- name: Set a variable
  set_fact:
    ssh_public_key: "{{ ssh_key.public_key }}"
    ssh_private_key: "{{ private_key.stdout }}"
  delegate_to: "{{agent_host}}"