---
# #tasks file for prerequisites
- name: Install docker dependencies
  become_user : "{{ root_user }}"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-apt  
    #update_cache: true
# - name: Add docker gpg key
#   become_user : "{{ root_user }}"
#   ansible.builtin.apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present
#     keyring: /etc/apt/keyrings/docker.gpg

# - name: Add docker repository
#   become_user : "{{ root_user }}"
#   ansible.builtin.apt_repository:
#     filename: docker
#     repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable
#     state: present

- name: Install docker engine
  become_user : "{{ root_user }}"
  ansible.builtin.apt:
    name:
      - docker-io
      #- docker-io-cli
      #- containerd.io
      - docker-buildx-plugin
      - docker-scan-plugin
      - docker-compose-plugin
    #update_cache: true
- name: install python package manager
  become_user : "{{ root_user }}"
  apt: 
    name: python3-pip
- name: install python docker sdk
  become_user : "{{ root_user }}"
  pip:
  
    name:
      - docker
      - docker-compose 
