apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-prod-v1
  labels:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
   # prometheus.io/path: "/api/v2/metrics"
spec:
  service_type: nodeport
  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 14Gi
