---
# tasks file for jenkins
- name: create project folder for jenkins
  file: 
    path: "{{jenkins_dir}}"
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000
- name: create mount folder for jenkins home
  file: 
    path: "{{jenkins_dir}}/jenkins_home"
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000
- name: create mount folder for jenkins docker
  file: 
    path: "{{jenkins_dir}}/jenkins_docker"
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000
- name: copy jenkins docker compose file 
  template:
    src: ../files/jenkins_service.yml.j2
    dest: "{{jenkins_dir}}/jenkins_service.yml"
    mode: '0644'
- name: destroy existing jenkins service
  become_user : root
  community.docker.docker_compose_v2:
    project_src: "{{jenkins_dir}}"
    files:
      - jenkins_service.yml
    state: absent
- name: Create and start jenkins service
  community.docker.docker_compose_v2:
    project_src: "{{jenkins_dir}}"
    files:
      - jenkins_service.yml
    state: present
- name: Wait for Jenkins to Start
  wait_for:
    port: 8080
    delay: 10
    timeout: 300
  register: jenkins_available
- name: Wait for Jenkins admin password file to be created
  wait_for:
    path: "{{ jenkins_dir }}/jenkins_home/secrets/initialAdminPassword"
    state: present
    delay: 10  # Initial delay before checking the file
    timeout: 400  # Total time to wait for the file
  register: file_wait
  when: jenkins_available  # Ensure Jenkins is set up before checking

- name: Get the initial admin password for Jenkins
  shell: cat "{{ jenkins_dir }}/jenkins_home/secrets/initialAdminPassword"
  register: password
  when: file_wait  # Execute only if the file was found
  notify: Print Initial Admin Password
