version: '3.6'
services:
  traefik:
    restart: always
    #labels:
    #- "traefik.http.routers.dashboard.rule=Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
    #- "traefik.http.routers.dashboard.service=api@internal"
    #- "traefik.http.routers.dashboard.middlewares=auth"
    #- "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
    container_name: traefik
    # The official v3 Traefik docker image
    image: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      # - "--api.insecure=true"
      # - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.websecure.address=:443"


    ports:

      # The HTTPS port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8090:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
#     networks:
#       gitlab_network:
#         ipv4_address: 172.18.0.4
networks:
  default:
    name: tr_network
#     driver: bridge
#     ipam:
#       config:
#       -
#         subnet: 172.18.0.0/16