apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx-prometheus-alertmanager
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/awx-prometheus-alertmanager"
