---
# tasks file for traefik
- name: create project folder for traefik
  file: 
    path: "{{traefik_dir}}"
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000
- name: copy traefik config file 
  copy:
    src: ../files/traefik.yml
    dest: "{{traefik_dir}}"
    mode: '0644'
- name: copy traefik compose file 
  copy:
    src: ../files/traefik_service.yml
    dest: "{{traefik_dir}}"
    mode: '0644'
- name: destroy existing traefik service
  become_user : root
  community.docker.docker_compose_v2:
    project_src: "{{traefik_dir}}"
    files:
      - traefik_service.yml
    state: absent
- name: Create and start traefik service
  community.docker.docker_compose_v2:
    project_src: "{{traefik_dir}}"
    files:
      - traefik_service.yml
    state: present